# Generated by Django 5.2.7 on 2025-10-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flaky_fantasy_backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
