# Generated by Django 4.2.7 on 2026-04-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flaky_fantasy_backend_api", "0002_remove_category_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
